apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: app-cron
  namespace: api
spec:
  selector:
    matchLabels:
      io.test.service: app-cron
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.test.service: app-cron
    spec:
      containers:
        - name: cron
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.tag }}"
          command: ["python3", "cron.py"]
      restartPolicy: Always
status: {}
