apiVersion: v1
kind: Service
metadata:
  namespace: api
  creationTimestamp: null
  labels:
    io.dflow.service: app-api
  name: app-api
spec:
  ports:
    - port: {{ .Values.web.port }}
      protocol: TCP
  selector:
    io.dflow.service: app-api
