apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: app-worker
  namespace: api
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4        # how many pods we can add at a time
      maxUnavailable: 2  # maxUnavailable define how many pods can be unavailable during the rolling update
  selector:
    matchLabels:
      io.dflow.service: app-worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.dflow.service: app-worker
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: {{ .Values.node.env }}
            - name: NODE_OPTIONS
              value: --max-old-space-size=1536
            - name: RUNNER
              value: api
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["python3", "worker"]
          name: app-worker

          resources:
            limits:
              cpu: 0.6
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 384Mi
      restartPolicy: Always
status: {}
