apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::491085427149:role/dflow-production-eks-spot-eks-node-group-20250115210022606000000004
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::491085427149:role/dflow-production-eks-spot-eks-node-group-20250115210022606000000004
      username: dflow-production-eks-spot-eks-node-group-20250115210022606000000004
      groups:
        - system:masters
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::491085427149:user/work-trial-hoop
      groups:
        - system:masters
        - system:bootstrappers
        - system:nodes
      username: work-trial-hoop
